# 预约参数配置
venue_type: "羽毛球场"  # 可选：羽毛球场、网球场、乒乓球
participants: "4"

# | 代号 | 时间段 |
# |------|--------|
# | 1 | 11:00-12:00 |
# | 2 | 12:00-13:00 |
# | 3 | 13:00-14:00 |
# | 4 | 14:00-15:00 |
# | 5 | 15:00-16:00 |
# | 6 | 16:00-17:00 |
# | 7 | 17:00-18:00 |
# | 8 | 18:00-19:00 |
# | 9 | 19:00-20:00 |
# | 10 | 20:00-21:00 |
# | 11 | 21:00-22:00 |

time_value: "6"

  # "羽毛球场": [
  #     "63_13",  # 羽毛球1号场地
  #     "63_14",  # 羽毛球2号场地
  #     "63_15",  # 羽毛球3号场地
  #     "63_16",  # 羽毛球4号场地
  #     "63_17",  # 羽毛球5号场地
  #     "63_18"   # 羽毛球6号场地
  # ],
  # "网球场": [
  #     "63_19",  # 网球1号场地
  #     "63_20",  # 网球2号场地
  #     "63_21",  # 网球3号场地
  #     "63_22"   # 网球4号场地
  # ],
  # "乒乓球": [
  #     "63_23",  # 乒乓球1号场地
  #     "63_24",  # 乒乓球2号场地
  #     "63_25",  # 乒乓球3号场地
  #     "63_26"   # 乒乓球4号场地
  # ]

venue_value: "63_17"  # 羽毛球1-6号：63_13~63_18
people_category: "学生"
third_party: "无"
phone: "19858214897"
take_charge_person: "张嘉杰"
usage_date: "2025-3-06"

# 登录信息
student_id: "2023233216"
password: "ZHANGjiajie123"
